name: Build Android Debug APK

on:
  workflow_dispatch:        # تشغيل يدوي من تبويب Actions
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # سيرفر لينكس من GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          target: default
          arch: x86_64
          profile: default
          emulator: false

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-SoundWaveApp-apk
          path: app/build/outputs/apk/debug/app-debug.apk